### ISSUE TITLE
Cannot run app

### ISSUE THREAD

**Issue by vi-ap** [betsegaw/menote#1]
Attempting to run win-run.bat gives me the following error message:
'.\bin\electron\electron.exe' is not recognized as an internal or external command, operable program or batch file.

**Comment by betsegaw** [comment]
My mistake. One of my .gitignore files from somewhere was causing the actual electron executable not to be added. To solve this, I force added them to the repo, which means the repo is now pretty large but its okay. Just tested this by downloading it as a zip to my machine from github and running it. Let me know if you are still having issues.

Fixed in : 8efa885136c681d6259fd3d3c066a94ccb2607d6
